{
 "title": "Confluent Open Source",
 "tags": [ "5.3.0" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "Environment",
    "query": "label_values({__name__=~\"cp_kafka_connect_connect_metrics_.+\"}, env)"
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values({__name__=~\"cp_kafka_connect_connect_metrics_.+\", env=~\"$env\"}, cluster)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values({__name__=~\"cp_kafka_connect_connect_metrics_.+\", env=\"$env\",cluster=\"$cluster\"}, service_instance)"
   },
   {
    "name": "connector",
    "label": "Connector",
    "query": "label_values({__name__=\"cp_kafka_connect_connect_connector_task_error_metrics_total_record_failures\", env=\"$env\",cluster=\"$cluster\"}, connector)"
   }
  ]
 },
 "panels": [
  {
   "title": "Confluent Kafka Connect Cluster: $env - $cluster",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Connector Startups",
   "type": "graph",
   "description": "The total number of connector starts that succeeded or failed",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_connector_startup_success_total{env=\"$env\",cluster=\"$cluster\"})",
     "legendFormat": "Successes"
    },
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_connector_startup_failure_total{env=\"$env\",cluster=\"$cluster\"})",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Connector Startups by Worker",
   "type": "graph",
   "description": "The total number of connector starts that succeeded or failed",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_connector_startup_success_total{env=\"$env\",cluster=\"$cluster\"}",
     "legendFormat": "{{service_instance}} Success"
    },
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_connector_startup_failure_total{env=\"$env\",cluster=\"$cluster\"}",
     "legendFormat": "{{service_instance}} Failed"
    }
   ]
  },
  {
   "title": "Task Startups",
   "type": "graph",
   "description": "The total number of task starts that succeeded or failed",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_task_startup_success_total{env=\"$env\",cluster=\"$cluster\"})",
     "legendFormat": "Successes"
    },
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_task_startup_failure_total{env=\"$env\",cluster=\"$cluster\"})",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "Task Startups by Worker",
   "type": "graph",
   "description": "The total number of task starts that succeeded or failed",
   "gridPos": { "h": 3, "w": 16, "x": 8, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_task_startup_success_total{env=\"$env\",cluster=\"$cluster\"}",
     "legendFormat": "{{service_instance}} Success"
    },
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_task_startup_failure_total{env=\"$env\",cluster=\"$cluster\"}",
     "legendFormat": "{{service_instance}} Failed"
    }
   ]
  },
  {
   "title": "Number of Connectors",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_connector_count{env=\"$env\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Connectors",
   "type": "table",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 7 },
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_connector_metrics{env=\"$env\",cluster=\"$cluster\",version=~\".+\"}",
     "legendFormat": "{{connector}}"
    },
    {
     "expr": "cp_kafka_connect_connect_connector_metrics{env=\"$env\",cluster=\"$cluster\",status=~\".+\"}",
     "legendFormat": "{{connector}}"
    },
    {
     "expr": "cp_kafka_connect_connect_connector_metrics{env=\"$env\",cluster=\"$cluster\",connector_type=~\".+\"}",
     "legendFormat": "{{connector}}"
    },
    {
     "expr": "cp_kafka_connect_connect_connector_metrics{env=\"$env\",cluster=\"$cluster\",class=~\".+\"}",
     "legendFormat": "{{connector}}"
    },
    {
     "expr": "cp_kafka_connect_connect_connector_metrics{env=\"$env\",cluster=\"$cluster\",class=~\".+\"}",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Number of Tasks",
   "type": "singlestat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(cp_kafka_connect_connect_worker_metrics_task_count{env=\"$env\",cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Task Assignments",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_worker_metrics_task_count{env=\"$env\",cluster=\"$cluster\"}",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Connect Metrics: Network IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "iops" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_metrics_incoming_byte_rate{env=\"$env\", cluster=\"$cluster\"}",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Connect Metrics: IO Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cp_kafka_connect_connect_metrics_io_ratio",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  { "title": "Worker $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 }, "repeat": "instance" },
  {
   "title": "JVM Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "((java_lang_memory_heapmemoryusage_used{env=\"$env\", cluster=\"$cluster\", service_instance=\"$instance\"} / java_lang_memory_heapmemoryusage_max{env=\"$env\", cluster=\"$cluster\", service_instance=\"$instance\"}) * 100)",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Task Records Skipped",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 27 },
   "yaxes": [
    { "format": "short", "label": "Skipped" }
   ],
   "targets": [
    {
     "expr": "sum by (connector, task) (rate(cp_kafka_connect_connect_connector_task_error_metrics_total_records_skipped{env=\"$env\",cluster=\"$cluster\",service_instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Task Startup Failure Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 31 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "rate(cp_kafka_connect_connect_worker_metrics_task_startup_failure_total{env=\"$env\", cluster=\"$cluster\", service_instance=\"$instance\"}[1m])",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Task Record Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "Failures" }
   ],
   "targets": [
    {
     "expr": "sum by (connector, task) (rate(cp_kafka_connect_connect_connector_task_error_metrics_total_record_failures{env=\"$env\",cluster=\"$cluster\",service_instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "${connector} Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 35 },
   "repeat": "connector",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cp_kafka_connect_connect_connector_task_error_metrics_total_retries{env=\"$env\",cluster=\"$cluster\",service_instance=\"$instance\",connector=~\"$connector\"}) or vector(0)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "${connector} Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 39 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cp_kafka_connect_connect_connector_task_error_metrics_total_retries{env=\"$env\",cluster=\"$cluster\",service_instance=\"$instance\",connector=~\"$connector\"}) or vector(0)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Task Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by (connector, task) (rate(cp_kafka_connect_connect_connector_task_error_metrics_total_errors_logged{env=\"$env\",cluster=\"$cluster\",service_instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "${connector} Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 43 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cp_kafka_connect_connect_connector_task_error_metrics_total_retries{env=\"$env\",cluster=\"$cluster\",service_instance=\"$instance\",connector=~\"$connector\"}) or vector(0)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  { "title": "Worker $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "JVM Heap Usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "((java_lang_memory_heapmemoryusage_used{env=\"$env\", cluster=\"$cluster\", service_instance=\"$instance\"} / java_lang_memory_heapmemoryusage_max{env=\"$env\", cluster=\"$cluster\", service_instance=\"$instance\"}) * 100)",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Task Records Skipped",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 48 },
   "yaxes": [
    { "format": "short", "label": "Skipped" }
   ],
   "targets": [
    {
     "expr": "sum by (connector, task) (rate(cp_kafka_connect_connect_connector_task_error_metrics_total_records_skipped{env=\"$env\",cluster=\"$cluster\",service_instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "Task Startup Failure Percentage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 52 },
   "format": "percent",
   "valueName": "max",
   "targets": [
    {
     "expr": "rate(cp_kafka_connect_connect_worker_metrics_task_startup_failure_total{env=\"$env\", cluster=\"$cluster\", service_instance=\"$instance\"}[1m])",
     "legendFormat": "{{service_instance}}"
    }
   ]
  },
  {
   "title": "Task Record Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "Failures" }
   ],
   "targets": [
    {
     "expr": "sum by (connector, task) (rate(cp_kafka_connect_connect_connector_task_error_metrics_total_record_failures{env=\"$env\",cluster=\"$cluster\",service_instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "${connector} Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 56 },
   "repeat": "connector",
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cp_kafka_connect_connect_connector_task_error_metrics_total_retries{env=\"$env\",cluster=\"$cluster\",service_instance=\"$instance\",connector=~\"$connector\"}) or vector(0)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "${connector} Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 60 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cp_kafka_connect_connect_connector_task_error_metrics_total_retries{env=\"$env\",cluster=\"$cluster\",service_instance=\"$instance\",connector=~\"$connector\"}) or vector(0)",
     "legendFormat": "{{connector}}"
    }
   ]
  },
  {
   "title": "Task Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 60 },
   "yaxes": [
    { "format": "short", "label": "Errors" }
   ],
   "targets": [
    {
     "expr": "sum by (connector, task) (rate(cp_kafka_connect_connect_connector_task_error_metrics_total_errors_logged{env=\"$env\",cluster=\"$cluster\",service_instance=~\"$instance\"}[1m]))",
     "legendFormat": "{{connector}}-{{task}}"
    }
   ]
  },
  {
   "title": "${connector} Tasks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 64 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(cp_kafka_connect_connect_connector_task_error_metrics_total_retries{env=\"$env\",cluster=\"$cluster\",service_instance=\"$instance\",connector=~\"$connector\"}) or vector(0)",
     "legendFormat": "{{connector}}"
    }
   ]
  }
 ]
}